application: ae-people
version: 1
runtime: python
api_version: 1

builtins:
- appstats: on
- remote_api: on

handlers:
- url: /static
  static_dir: static
 
- url: /.*
  script: main.py  

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (django.zip)|
 (django/.*)|
 (dev_settings.py)|
 )$
