application: ae-people
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py


- url: /_ah/.*
  script: admin.py
  login: admin

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
 
- url: /.*
  script: main.py  

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (django.zip)|
 (django/.*)|
 (dev_settings.py)|
 )$
